# Generated by Django 4.2.6 on 2023-10-09 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggybank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piggybank',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='piggy_bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='piggybank.piggybank'),
        ),
    ]
